CREATE DATABASE moviepass;

USE moviepass;

CREATE TABLE IF NOT EXISTS users(
	mail VARCHAR(50) NOT NULL,
	pass VARCHAR(50) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (mail),
	CONSTRAINT unq_mail UNIQUE (mail)
);
